import{a as b,S as w,i as c}from"./assets/vendor-BfjKTZs6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const L="49359738-1a7aad8ecd2da3da8f5235c9c",S="https://pixabay.com/api/";async function f(t,r=1,s=15){try{const a=await b.get(S,{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:r}});return{images:a.data.hits,totalHits:a.data.totalHits}}catch(a){return console.error("Помилка отримання даних:",a),{images:[],totalHits:0}}}const q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function v(t){return t.map(({webformatURL:r,largeImageURL:s,tags:a,likes:e,views:o,comments:l,downloads:h})=>`
      <a class="gallery-item" href="${s}">
        <img src="${r}" alt="${a}" loading="lazy"/>
        <div class="info">
          <p><b>Likes:</b> ${e}</p>
          <p><b>Views:</b> ${o}</p>
          <p><b>Comments:</b> ${l}</p>
          <p><b>Downloads:</b> ${h}</p>
        </div>
      </a>`).join("")}function g(t,r){t.insertAdjacentHTML("beforeend",v(r)),q.refresh()}function H(t){t.innerHTML=""}const P=document.querySelector("#search-form"),p=document.querySelector(".gallery"),n=document.querySelector(".load-more"),y=document.querySelector(".loader");let d="",i=1;const u=15;let m=0;n.style.display="none";y.style.display="none";P.addEventListener("submit",async t=>{if(t.preventDefault(),d=t.target.elements.searchQuery.value.trim(),!d){c.error({message:"Please enter a search query."});return}H(p),i=1,n.style.display="none",y.style.display="block";try{const{images:r,totalHits:s}=await f(d,i,u);if(m=s,r.length===0){c.warning({message:"No images found. Try another search."});return}g(p,r),n.style.display=i*u<m?"block":"none"}catch{c.error({message:"Something went wrong. Please try again."})}finally{y.style.display="none"}});n.addEventListener("click",async()=>{i+=1,n.style.display="none",y.style.display="block";try{const{images:t}=await f(d,i,u);if(t.length>0){g(p,t);const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}i*u>=m?(n.style.display="none",c.info({message:"We're sorry, but you've reached the end of search results."})):n.style.display="block"}catch{c.error({message:"Something went wrong. Please try again."})}finally{y.style.display="none"}});
//# sourceMappingURL=index.js.map
