import{a as g,S as h,i as l}from"./assets/vendor-BfjKTZs6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const o of a.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function c(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(e){if(e.ep)return;e.ep=!0;const a=c(e);fetch(e.href,a)}})();const y="49359738-1a7aad8ecd2da3da8f5235c9c",f="https://pixabay.com/api/";class m{constructor(){this.query="",this.page=1,this.perPage=15,this.totalHits=0}async fetchImages(){try{const t=await g.get(f,{params:{key:y,q:this.query,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:this.perPage,page:this.page}});return this.totalHits=t.data.totalHits,t.data.hits}catch(t){return console.error("Помилка отримання даних:",t),[]}}resetPage(){this.page=1}nextPage(){this.page+=1}hasMorePages(){return this.page*this.perPage<this.totalHits}}function b(r){return r.map(({webformatURL:t,largeImageURL:c,tags:i,likes:e,views:a,comments:o,downloads:d})=>`
      <a class="gallery-item" href="${c}">
        <img src="${t}" alt="${i}" loading="lazy"/>
        <div class="info">
          <p><b>Likes:</b> ${e}</p>
          <p><b>Views:</b> ${a}</p>
          <p><b>Comments:</b> ${o}</p>
          <p><b>Downloads:</b> ${d}</p>
        </div>
      </a>`).join("")}function p(r,t){r.insertAdjacentHTML("beforeend",b(t)),L.refresh()}function P(r){r.innerHTML=""}const L=new h(".gallery a",{captionsData:"alt",captionDelay:250}),q=document.querySelector("#search-form"),u=document.querySelector(".gallery"),n=document.querySelector(".load-more"),s=new m;q.addEventListener("submit",async r=>{if(r.preventDefault(),s.query=r.target.elements.searchQuery.value.trim(),!s.query){l.error({message:"Please enter a search query."});return}s.resetPage(),P(u),n.style.display="none";const t=await s.fetchImages();if(t.length===0){l.warning({message:"No images found. Try another search."});return}p(u,t),n.style.display=s.hasMorePages()?"block":"none"});n.addEventListener("click",async()=>{s.nextPage();const r=await s.fetchImages();r.length>0&&(p(u,r),window.scrollBy({top:document.querySelector(".gallery-item").getBoundingClientRect().height*2,behavior:"smooth"})),s.hasMorePages()||(n.style.display="none",l.info({message:"We're sorry, but you've reached the end of search results."}))});
//# sourceMappingURL=index.js.map
